### PR TITLE
Report extension feature viewer

### PR DESCRIPTION
**Pull request by isanchez-c2c**

### CODE REVIEW

**Comment by tonio** [comment]
Nice, but what about simplifying down to: 

Screenshot 2021-05-04 at 09-28-23 Template project to create MapStore extensions

```jsx
    render() {
        const { properties } = this.props.feature;

        return (
            <ul>
                {Object.keys(properties).map((prop, i) => (
                    <li>
                        <strong>{prop}:</strong> {properties[prop]}
                    </li>
                ))}
            </ul>
        );
    }
```

Then you can maybe inline it in `FeatureReport` & avoid another component.

**Comment by isanchez-c2c** [comment]
ok, I wasn't sure if the geometry was needed, and as the geometry is much easier displayable with JSON.stringify (which needs `<pre>` for nice printing), I tried to keep some consistency in the display.
Ok for avoiding another component ;)

**Comment by isanchez-c2c** [comment]
changed

**Review by tonio — APPROVED** [review]
:shipit:

**Pull request merged**
